### ISSUE TITLE
Bar chart support?

### ISSUE THREAD

**Issue by auggod** [hansmaad/chartist-logaxis#1]
If i'm using the plugin with a bar chart, chrome gives a snap error after hanging a few seconds. Any ideas?

Thanks for this plugin though!

**Comment by hansmaad** [comment]
Your chart must not have 0 values. By default the lower bar chart bound is set to 0, which doesn't make sense on logarithmic scales. You have to manually set `low` in your chart options.
Example:
https://stackblitz.com/edit/chartist-log-bar

**Comment by auggod** [comment]
Got it! Thank you.
